local ret = {title="credits", buttons={{str = 'back', action = 'back'}}} --back button and one space between this and the actual credits

local credits = {
"",
"programming", 
"     minds3t", 
"", 
"spriting",
"     minds3t",
"     harvester",
"     shypixels",
"     derahex (hexstar)",
"     gummy (souleater)",
"     neibern (fruit salad)",
"",
"room design",
"     minds3t",
"     busybody64",
"",
"music and sound",
"     minds3t",
"     nihil (observatory)",
"     kharjaro (mastering)",
"concepts",
"     minds3t",
"     shypixels",
"     kharjaro",
"     derahex (hexstar)",
"     reactive (bombshell)",
"     sdar (bubbly plum", 
"blightfly, enemy and",
"pickup tweaks)",
"     harvester",
"",
"wiki editors",
"     snopingas",
"     minds3t",
"     andredoruk",
"",
"beta testers <3",
"     anon.",
"     daddynature",
"     emster",
"     gamer24320",
"     izzyisakoi_",
"     leclair a la vanille",
"     lamb",
"     sdar",
"     snopingas",
"     voidro",
"     zek",
"     coyote",
"     finalrun36",
"     kharjaro",
"     hikikomori",
"     sallyspartan",
"     carlosmann100",
"     actualjohndear",
"    gokudera elpsycongroo",
"     arthurkyl",
"     toad enjoyer !! :D",
"     gigachaddarko",
"     busybody64",
"     delta",
"     dontstopmegalo",
"     krepa",
"     lidor",
"     m33bored",
"     slimly",
"     timur2009",
"",
"a cutie patootie",
"     you :)",
"",
" thank u 4 playing!",
" - minds3t and co.",
""
}

for i,line in ipairs(credits) do 
    table.insert(ret.buttons, {
        str = line,
        fsize = (i > 1 and credits[i - 1] == ""     and 3 or 2),
        nosel = i > 1 and credits[i - 1] == "" or line == "",
    })
end

table.insert(ret.buttons, {str = 'back', action = 'back'})

return ret 