local ret = {title="credits", buttons={{str = 'back', action = 'back'}}} --back button and one space between this and the actual credits

local credits = {
"",
"programming", 
"     minds3t", 
"", 
"spriting",
"     minds3t",
"     harvester",
"     shypixels",
"     derahex (hexstar)",
"     gummy (souleater)",
"     neibern (fruit salad)",
"",
"room design",
"     minds3t",
"     busybody64",
"",
"music and sound",
"     minds3t",
"     nihil (observatory)",
"     kharjaro (mastering)",
"concepts",
"     minds3t",
"     shypixels",
"     kharjaro",
"     derahex (hexstar)",
"     reactive (bombshell)",
"     sdar (bubbly plum", 
"blightfly, enemy and",
"pickup tweaks)",
"     harvester",
"",
"wiki editors",
"     snopingas",
"     minds3t",
"     andredoruk",
"",
"beta testers <3",
"     anon.",
"     daddynature",
"     emster",
"     gamer243209884",
"     izzyisakoi",
"     leclairalavanille",
"     lamb2308",
"     sdar8698",
"     snopingas",
"     voidro",
"     zek",
"     coyote",
"     finalrun36",
"     kharjaro",
"     sensorydetails",
"     sallyspartan",
"     carlosmann100",
"     actualjohndear",
"    gokudera elpsycongroo",
"     arthurkyl",
"     aphyxii",
"     gigachaddarko",
"     busybody64",
"     its.a.corpse",
"     dontstopmegalo",
"     akrepa",
"     lidor5653",
"     m33bored",
"     slimly2",
"     timur20097801",
"     _taley_",
"     agav00",
"     aaaki_",
"     d06135",
"     wooliee",
"     bredzisz",
"     tcbudders",
"     buididipi",
"     chalupa3401",
"     coin_0440",
"     asade0885",
"     bagman64",
"     busybody64_0107",
"     flowingredscales",
"     evbakim",
"     falcofulvus",
"     fly_6",
"     iateurcookies",
"     galaxyjam",
"     generic1110",
"     hunkypluck",
"     icenek",
"     j0shyii",
"     kazeanemo",
"     kinglime_",
"     akrepa",
"     lonson77",
"     millieamp",
"     doodboy",
"     raikuthedragon",
"     samhem123",
"     al1sh0ck",
"     shromo0",
"     susukethereal",
"     surpos",
"     falseopulence",
"     tuomas9558",
"     ultrinik",
"",
"a cutie patootie",
"     you :)",
"",
" thank u 4 playing!",
" - minds3t and co.",
""
}

for i,line in ipairs(credits) do 
    table.insert(ret.buttons, {
        str = line,
        fsize = (i > 1 and credits[i - 1] == ""     and 3 or 2),
        nosel = i > 1 and credits[i - 1] == "" or line == "",
    })
end

table.insert(ret.buttons, {str = 'back', action = 'back'})

return ret 