local ret = {}
table.insert(ret, include("scripts.definitions.entities.monster.arch_bishop"))
table.insert(ret, include("scripts.definitions.entities.monster.barfer"))
table.insert(ret, include("scripts.definitions.entities.monster.big_dipper"))
table.insert(ret, include("scripts.definitions.entities.monster.blind"))
table.insert(ret, include("scripts.definitions.entities.monster.blood_baby"))
table.insert(ret, include("scripts.definitions.entities.monster.blue_horf"))
table.insert(ret, include("scripts.definitions.entities.monster.blue_fatty"))
table.insert(ret, include("scripts.definitions.entities.monster.callen_skull"))
table.insert(ret, include("scripts.definitions.entities.monster.chanter"))
table.insert(ret, include("scripts.definitions.entities.monster.chest_mimic"))
table.insert(ret, include("scripts.definitions.entities.monster.cluster"))
table.insert(ret, include("scripts.definitions.entities.monster.delirious_pile"))
table.insert(ret, include("scripts.definitions.entities.monster.dial"))
table.insert(ret, include("scripts.definitions.entities.monster.drifter"))
table.insert(ret, include("scripts.definitions.entities.monster.dream"))
table.insert(ret, include("scripts.definitions.entities.monster.electrite"))
table.insert(ret, include("scripts.definitions.entities.monster.fallen_angel"))
table.insert(ret, include("scripts.definitions.entities.monster.fetal_baby"))
table.insert(ret, include("scripts.definitions.entities.monster.gatekeeper"))
table.insert(ret, include("scripts.definitions.entities.monster.godleg"))
table.insert(ret, include("scripts.definitions.entities.monster.grub"))
table.insert(ret, include("scripts.definitions.entities.monster.guarded"))
table.insert(ret, include("scripts.definitions.entities.monster.guard_of_the_father"))
table.insert(ret, include("scripts.definitions.entities.monster.harf"))
table.insert(ret, include("scripts.definitions.entities.monster.hexstar"))
table.insert(ret, include("scripts.definitions.entities.monster.hover"))
table.insert(ret, include("scripts.definitions.entities.monster.infested_membrain"))
table.insert(ret, include("scripts.definitions.entities.monster.ludomini"))
table.insert(ret, include("scripts.definitions.entities.monster.marshall_pawn"))
table.insert(ret, include("scripts.definitions.entities.monster.mum"))
table.insert(ret, include("scripts.definitions.entities.monster.nerve_cluster"))
table.insert(ret, include("scripts.definitions.entities.monster.paracolony"))
table.insert(ret, include("scripts.definitions.entities.monster.planter"))
table.insert(ret, include("scripts.definitions.entities.monster.purple_mask"))
table.insert(ret, include("scripts.definitions.entities.monster.queen_fly"))
table.insert(ret, include("scripts.definitions.entities.monster.ratty"))
table.insert(ret, include("scripts.definitions.entities.monster.shade"))
table.insert(ret, include("scripts.definitions.entities.monster.silent"))
table.insert(ret, include("scripts.definitions.entities.monster.smasher"))
table.insert(ret, include("scripts.definitions.entities.monster.super_host"))
table.insert(ret, include("scripts.definitions.entities.monster.super_flesh_host"))
table.insert(ret, include("scripts.definitions.entities.monster.teether"))
table.insert(ret, include("scripts.definitions.entities.monster.the_id"))
table.insert(ret, include("scripts.definitions.entities.monster.trailer"))
table.insert(ret, include("scripts.definitions.entities.monster.vengeance"))
table.insert(ret, include("scripts.definitions.entities.monster.winged_spider"))
table.insert(ret, include("scripts.definitions.entities.monster.wrinkly_fatty"))

-- table.insert(ret, include("scripts.definitions.entities.boss.the_sunken"))
table.insert(ret, include("scripts.definitions.entities.boss.ludomaw"))
table.insert(ret, include("scripts.definitions.entities.boss.hostess"))
table.insert(ret, include("scripts.definitions.entities.boss.souleater"))
table.insert(ret, include("scripts.definitions.entities.boss.furnace_guard"))
table.insert(ret, include("scripts.definitions.entities.boss.grand_marshall"))
-- table.insert(ret, include("scripts.definitions.entities.boss.adramolech"))
-- table.insert(ret, include("scripts.definitions.entities.boss.lucifer"))
-- table.insert(ret, include("scripts.definitions.entities.boss.lucifer_nohealth"))
table.insert(ret, include("scripts.definitions.entities.boss.skeleton_angel"))
table.insert(ret, include("scripts.definitions.entities.boss.skeleton_soul"))
table.insert(ret, include("scripts.definitions.entities.boss.the_ritual"))
table.insert(ret, include("scripts.definitions.entities.boss.sacred_mind"))
table.insert(ret, include("scripts.definitions.entities.boss.sacred_body"))
table.insert(ret, include("scripts.definitions.entities.boss.sacred_soul"))
-- table.insert(ret, include("scripts.definitions.entities.boss.it_breathes"))
table.insert(ret, include("scripts.definitions.entities.boss.bloody_gabriel"))
table.insert(ret, include("scripts.definitions.entities.boss.bloody_uriel"))
table.insert(ret, include("scripts.definitions.entities.boss.bathemo"))
table.insert(ret, include("scripts.definitions.entities.boss.bathemo_swarm"))
table.insert(ret, include("scripts.definitions.entities.boss.mimic_worm"))
table.insert(ret, include("scripts.definitions.entities.boss.bubbly_plum"))
table.insert(ret, include("scripts.definitions.entities.boss.megaworm"))
table.insert(ret, include("scripts.definitions.entities.boss.blightfly"))
table.insert(ret, include("scripts.definitions.entities.boss.bowl_play"))
table.insert(ret, include("scripts.definitions.entities.boss.outbreak"))
table.insert(ret, include("scripts.definitions.entities.boss.bulge_bat"))
table.insert(ret, include("scripts.definitions.entities.boss.brazier"))
table.insert(ret, include("scripts.definitions.entities.boss.error"))

table.insert(ret, include("scripts.definitions.entities.boss.famine"))
table.insert(ret, include("scripts.definitions.entities.boss.war"))
table.insert(ret, include("scripts.definitions.entities.boss.war_no_horse"))
table.insert(ret, include("scripts.definitions.entities.boss.death"))
table.insert(ret, include("scripts.definitions.entities.boss.death_horse"))
table.insert(ret, include("scripts.definitions.entities.boss.death_no_horse"))

table.insert(ret, include("scripts.definitions.entities.effect.holy_order"))
table.insert(ret, include("scripts.definitions.entities.effect.unholy_order"))
table.insert(ret, include("scripts.definitions.entities.effect.shatter_coin"))
table.insert(ret, include("scripts.definitions.entities.effect.sign_flame"))
table.insert(ret, include("scripts.definitions.entities.effect.ivory_portal"))
-- table.insert(ret, include("scripts.definitions.entities.effect.furnace_bubble"))
table.insert(ret, include("scripts.definitions.entities.effect.crack_sky_with_tell"))
table.insert(ret, include("scripts.definitions.entities.effect.papal_flame"))
table.insert(ret, include("scripts.definitions.entities.effect.gold_scale"))
table.insert(ret, include("scripts.definitions.entities.effect.bone_shield"))
table.insert(ret, include("scripts.definitions.entities.effect.marketman"))
table.insert(ret, include("scripts.definitions.entities.effect.call_of_the_void"))
table.insert(ret, include("scripts.definitions.entities.effect.cat_swipe"))
table.insert(ret, include("scripts.definitions.entities.effect.fallen_light_crack"))
table.insert(ret, include("scripts.definitions.entities.effect.soft_serve_puddle"))
table.insert(ret, include("scripts.definitions.entities.effect.adra_charge"))
table.insert(ret, include("scripts.definitions.entities.effect.war_banner"))
table.insert(ret, include("scripts.definitions.entities.effect.door_hazard"))
table.insert(ret, include("scripts.definitions.entities.effect.player_trail"))
table.insert(ret, include("scripts.definitions.entities.effect.observatory_fx"))
table.insert(ret, include("scripts.definitions.entities.effect.correction_fx"))
table.insert(ret, include("scripts.definitions.entities.effect.fallen_light_bone"))

table.insert(ret, include("scripts.definitions.entities.pickup.secret_light"))
table.insert(ret, include("scripts.definitions.entities.pickup.red_coin"))
table.insert(ret, include("scripts.definitions.entities.pickup.heart_container"))
table.insert(ret, include("scripts.definitions.entities.pickup.fruit"))
table.insert(ret, include("scripts.definitions.entities.pickup.fatal_attraction"))
table.insert(ret, include("scripts.definitions.entities.pickup.sugar_pills"))

-- table.insert(ret, include("scripts.definitions.entities.machine.ivory_palace_decorator"))
table.insert(ret, include("scripts.definitions.entities.machine.elohim_throne"))
table.insert(ret, include("scripts.definitions.entities.machine.bomb_barrel"))
table.insert(ret, include("scripts.definitions.entities.machine.mask_statue"))
table.insert(ret, include("scripts.definitions.entities.machine.ooze_turret"))
table.insert(ret, include("scripts.definitions.entities.machine.trap_turret"))
table.insert(ret, include("scripts.definitions.entities.machine.palace_mural"))
table.insert(ret, include("scripts.definitions.entities.machine.secret_pedestal"))
table.insert(ret, include("scripts.definitions.entities.machine.dynamite_rock"))
table.insert(ret, include("scripts.definitions.entities.machine.pill_beggar"))
table.insert(ret, include("scripts.definitions.entities.machine.gehazi_shrine"))
table.insert(ret, include("scripts.definitions.entities.machine.correction_shrine"))
table.insert(ret, include("scripts.definitions.entities.machine.cotv_correct"))
table.insert(ret, include("scripts.definitions.entities.machine.closet_tchar"))

table.insert(ret, include("scripts.definitions.entities.familiar.burnt_page"))
table.insert(ret, include("scripts.definitions.entities.familiar.holy_chalice"))
table.insert(ret, include("scripts.definitions.entities.familiar.pair_of_cans"))
table.insert(ret, include("scripts.definitions.entities.familiar.hush_cannon"))
table.insert(ret, include("scripts.definitions.entities.familiar.chigger"))
table.insert(ret, include("scripts.definitions.entities.familiar.shop_parrot"))
table.insert(ret, include("scripts.definitions.entities.familiar.diya"))
table.insert(ret, include("scripts.definitions.entities.familiar.ritual_candle"))
table.insert(ret, include("scripts.definitions.entities.familiar.fallen_guard"))
table.insert(ret, include("scripts.definitions.entities.familiar.late_delivery"))
table.insert(ret, include("scripts.definitions.entities.familiar.fruit_fly"))
table.insert(ret, include("scripts.definitions.entities.familiar.deli_halo"))
table.insert(ret, include("scripts.definitions.entities.familiar.deli_eye"))
table.insert(ret, include("scripts.definitions.entities.familiar.vengeful_dagger"))

return ret