local ret = {}
table.insert(ret, include("scripts.definitions.monsters.nerve_cluster"))
table.insert(ret, include("scripts.definitions.monsters.guard_of_the_father"))
table.insert(ret, include("scripts.definitions.monsters.blind"))
table.insert(ret, include("scripts.definitions.monsters.dream"))
table.insert(ret, include("scripts.definitions.monsters.trailer"))
table.insert(ret, include("scripts.definitions.monsters.mum"))
table.insert(ret, include("scripts.definitions.monsters.grub"))
table.insert(ret, include("scripts.definitions.monsters.cluster"))
table.insert(ret, include("scripts.definitions.monsters.harf"))
table.insert(ret, include("scripts.definitions.monsters.purple_mask"))
table.insert(ret, include("scripts.definitions.monsters.smasher"))
table.insert(ret, include("scripts.definitions.monsters.planter"))
table.insert(ret, include("scripts.definitions.monsters.big_dipper"))
table.insert(ret, include("scripts.definitions.monsters.barfer"))
table.insert(ret, include("scripts.definitions.monsters.dial"))
table.insert(ret, include("scripts.definitions.monsters.guarded"))
table.insert(ret, include("scripts.definitions.monsters.silent"))
table.insert(ret, include("scripts.definitions.monsters.teether"))
table.insert(ret, include("scripts.definitions.monsters.hover"))
table.insert(ret, include("scripts.definitions.monsters.super_host"))
table.insert(ret, include("scripts.definitions.monsters.super_flesh_host"))
table.insert(ret, include("scripts.definitions.monsters.drifter"))
table.insert(ret, include("scripts.definitions.monsters.chanter"))
table.insert(ret, include("scripts.definitions.monsters.shade"))
table.insert(ret, include("scripts.definitions.monsters.paracolony"))
table.insert(ret, include("scripts.definitions.monsters.blood_baby"))
table.insert(ret, include("scripts.definitions.monsters.fallen_angel"))
table.insert(ret, include("scripts.definitions.monsters.queen_fly"))
table.insert(ret, include("scripts.definitions.monsters.godleg"))
table.insert(ret, include("scripts.definitions.monsters.marshall_pawn"))
table.insert(ret, include("scripts.definitions.monsters.arch_bishop"))
table.insert(ret, include("scripts.definitions.monsters.hexstar"))
table.insert(ret, include("scripts.definitions.monsters.the_id"))
table.insert(ret, include("scripts.definitions.monsters.gatekeeper"))
table.insert(ret, include("scripts.definitions.monsters.winged_spider"))
table.insert(ret, include("scripts.definitions.monsters.delirious_pile"))
table.insert(ret, include("scripts.definitions.monsters.ludomini"))
table.insert(ret, include("scripts.definitions.monsters.ratty"))
table.insert(ret, include("scripts.definitions.monsters.infested_membrain"))
table.insert(ret, include("scripts.definitions.monsters.wrinkly_fatty"))
table.insert(ret, include("scripts.definitions.monsters.fetal_baby"))
table.insert(ret, include("scripts.definitions.monsters.vengeance"))
table.insert(ret, include("scripts.definitions.monsters.devil_lock"))

-- table.insert(ret, include("scripts.definitions.monsters.boss.the_sunken"))
table.insert(ret, include("scripts.definitions.monsters.boss.ludomaw"))
table.insert(ret, include("scripts.definitions.monsters.boss.hostess"))
table.insert(ret, include("scripts.definitions.monsters.boss.souleater"))
table.insert(ret, include("scripts.definitions.monsters.boss.furnace_guard"))
table.insert(ret, include("scripts.definitions.monsters.boss.grand_marshall"))
-- table.insert(ret, include("scripts.definitions.monsters.boss.adramolech"))
-- table.insert(ret, include("scripts.definitions.monsters.boss.lucifer"))
-- table.insert(ret, include("scripts.definitions.monsters.boss.lucifer_nohealth"))
table.insert(ret, include("scripts.definitions.monsters.boss.skeleton_angel"))
table.insert(ret, include("scripts.definitions.monsters.boss.skeleton_soul"))
table.insert(ret, include("scripts.definitions.monsters.boss.the_ritual"))
table.insert(ret, include("scripts.definitions.monsters.boss.sacred_mind"))
table.insert(ret, include("scripts.definitions.monsters.boss.sacred_body"))
table.insert(ret, include("scripts.definitions.monsters.boss.sacred_soul"))
-- table.insert(ret, include("scripts.definitions.monsters.boss.it_breathes"))
table.insert(ret, include("scripts.definitions.monsters.boss.bloody_gabriel"))
table.insert(ret, include("scripts.definitions.monsters.boss.bloody_uriel"))
table.insert(ret, include("scripts.definitions.monsters.boss.bathemo"))
table.insert(ret, include("scripts.definitions.monsters.boss.bathemo_swarm"))
table.insert(ret, include("scripts.definitions.monsters.boss.mimic_worm"))
table.insert(ret, include("scripts.definitions.monsters.boss.bubbly_plum"))
table.insert(ret, include("scripts.definitions.monsters.boss.megaworm"))
table.insert(ret, include("scripts.definitions.monsters.boss.blightfly"))
table.insert(ret, include("scripts.definitions.monsters.boss.bowl_play"))
table.insert(ret, include("scripts.definitions.monsters.boss.outbreak"))
table.insert(ret, include("scripts.definitions.monsters.boss.bulge_bat"))

table.insert(ret, include("scripts.definitions.monsters.boss.famine"))
table.insert(ret, include("scripts.definitions.monsters.boss.war"))
table.insert(ret, include("scripts.definitions.monsters.boss.war_no_horse"))
table.insert(ret, include("scripts.definitions.monsters.boss.death"))
table.insert(ret, include("scripts.definitions.monsters.boss.death_horse"))
table.insert(ret, include("scripts.definitions.monsters.boss.death_no_horse"))

table.insert(ret, include("scripts.definitions.monsters.effect.holy_order"))
table.insert(ret, include("scripts.definitions.monsters.effect.unholy_order"))
table.insert(ret, include("scripts.definitions.monsters.effect.shatter_coin"))
table.insert(ret, include("scripts.definitions.monsters.effect.sign_flame"))
table.insert(ret, include("scripts.definitions.monsters.effect.ivory_portal"))
-- table.insert(ret, include("scripts.definitions.monsters.effect.furnace_bubble"))
table.insert(ret, include("scripts.definitions.monsters.effect.crack_sky_with_tell"))
table.insert(ret, include("scripts.definitions.monsters.effect.papal_flame"))
table.insert(ret, include("scripts.definitions.monsters.effect.gold_scale"))
table.insert(ret, include("scripts.definitions.monsters.effect.bone_shield"))
table.insert(ret, include("scripts.definitions.monsters.effect.marketman"))
table.insert(ret, include("scripts.definitions.monsters.effect.call_of_the_void"))
table.insert(ret, include("scripts.definitions.monsters.effect.cat_swipe"))
table.insert(ret, include("scripts.definitions.monsters.effect.fallen_light_crack"))
table.insert(ret, include("scripts.definitions.monsters.effect.soft_serve_puddle"))
table.insert(ret, include("scripts.definitions.monsters.effect.adra_charge"))
table.insert(ret, include("scripts.definitions.monsters.effect.war_banner"))
table.insert(ret, include("scripts.definitions.monsters.effect.door_hazard"))

table.insert(ret, include("scripts.definitions.monsters.pickup.secret_light"))
table.insert(ret, include("scripts.definitions.monsters.pickup.red_coin"))
table.insert(ret, include("scripts.definitions.monsters.pickup.heart_container"))
table.insert(ret, include("scripts.definitions.monsters.pickup.fruit"))
table.insert(ret, include("scripts.definitions.monsters.pickup.fatal_attraction"))

-- table.insert(ret, include("scripts.definitions.monsters.machine.pill_beggar"))
-- table.insert(ret, include("scripts.definitions.monsters.machine.ivory_palace_decorator"))
table.insert(ret, include("scripts.definitions.monsters.machine.elohim_throne"))
table.insert(ret, include("scripts.definitions.monsters.machine.bomb_barrel"))
table.insert(ret, include("scripts.definitions.monsters.machine.mask_statue"))
table.insert(ret, include("scripts.definitions.monsters.machine.ooze_turret"))
table.insert(ret, include("scripts.definitions.monsters.machine.trap_turret"))
table.insert(ret, include("scripts.definitions.monsters.machine.palace_mural"))
table.insert(ret, include("scripts.definitions.monsters.machine.secret_pedestal"))

table.insert(ret, include("scripts.definitions.monsters.tweaks.mimic"))

table.insert(ret, include("scripts.definitions.monsters.familiar.burnt_page"))
table.insert(ret, include("scripts.definitions.monsters.familiar.holy_chalice"))
table.insert(ret, include("scripts.definitions.monsters.familiar.pair_of_cans"))
table.insert(ret, include("scripts.definitions.monsters.familiar.hush_cannon"))
table.insert(ret, include("scripts.definitions.monsters.familiar.chigger"))
table.insert(ret, include("scripts.definitions.monsters.familiar.shop_parrot"))
table.insert(ret, include("scripts.definitions.monsters.familiar.diya"))
table.insert(ret, include("scripts.definitions.monsters.familiar.ritual_candle"))
table.insert(ret, include("scripts.definitions.monsters.familiar.fallen_guard"))
table.insert(ret, include("scripts.definitions.monsters.familiar.late_delivery"))
table.insert(ret, include("scripts.definitions.monsters.familiar.fruit_fly"))

return ret